/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.studio.lpoo_studiodanca.view;

import br.edu.ifsul.cc.lpoo.studio.lpoo_studiodanca.dao.PersistenciaJPA;
import br.edu.ifsul.cc.lpoo.studio.lpoo_studiodanca.model.Modalidade;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.junit.After;
import org.junit.Before;

/**
 *
 * @author Nicolas Scopel
 */
public class TelaModalidades extends javax.swing.JFrame {

    DefaultListModel<Modalidade> mascaraItemLista = new DefaultListModel<>();

    /**
     * Creates new form TelaModalidades
     */
    public TelaModalidades() {

        initComponents();
        lstModalidades.clearSelection();
        // passar lista modelo para o componente JList
        lstModalidades.setModel(mascaraItemLista);

        mostraModalidades();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstModalidades = new javax.swing.JList<>();
        btnNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDescricaoBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstModalidades);

        btnNovo.setText("Nova");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista Modalidades");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição: ");

        txtDescricaoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoBuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnNovo)
                        .addGap(61, 61, 61)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemover)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescricaoBusca))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricaoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostraModalidades() {

        PersistenciaJPA jpa = new PersistenciaJPA();
        jpa.conexaoAberta();

        List<Modalidade> modalidades = jpa.getModalidades();
        mascaraItemLista.clear();

        for (Modalidade Modalidade : modalidades) {
            mascaraItemLista.addElement(Modalidade);

        }
        lstModalidades.setModel(mascaraItemLista);
        jpa.fecharConexao();
    }


    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:

        PersistenciaJPA jpa = new PersistenciaJPA();
        Modalidade m = new Modalidade();
        String desc;
        desc = JOptionPane.showInputDialog(rootPane, "Informe a Descrição da Modalidade");
        System.out.println(desc);
        m.setDescricao(desc);

        //listaModalidades.add(desc);
        try {
            jpa.persist(m);
        } catch (Exception ex) {

        }

        mascaraItemLista.addElement(m);

        jpa.fecharConexao();

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Modalidade modalidadeSelecionada =  lstModalidades.getSelectedValue();
        //PersistenciaJPA jpa = new PersistenciaJPA();
        
        if(modalidadeSelecionada != null){

          /*
            try {
                
               
                jpa.conexaoAberta();
                
                Modalidade modalidadePersistido = (Modalidade)jpa.find(Modalidade.class, modalidadeSelecionada.getId());
                modalidadePersistido.setDescricao(JOptionPane.showInputDialog(rootPane,"Informe a descricao nova",modalidadeSelecionada.getDescricao()));
                
                jpa.persist(modalidadePersistido);
                
                jpa.fecharConexao();
                mostraModalidades();
                 
                
            } catch (Exception ex) {
                System.out.println("Erro ao alterar modalidade selecionada: ");

            } finally {
                jpa.fecharConexao();
            }
            */
                
                    
                TelaCadastroModalidade dialog = new TelaCadastroModalidade(this, true);
                dialog.setModalidade(modalidadeSelecionada);
                dialog.setVisible(true);
                mostraModalidades();
                
                
                
          
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        Modalidade modalidadeSelecionada = lstModalidades.getSelectedValue();
        PersistenciaJPA jpa = new PersistenciaJPA();
        
        if(modalidadeSelecionada != null){
            int confirmPanel = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover a modalidade? " + modalidadeSelecionada);

        if (confirmPanel == JOptionPane.YES_OPTION) {

            try {

                jpa.conexaoAberta();
                jpa.remover(modalidadeSelecionada);
                jpa.fecharConexao();
                mostraModalidades();
            } catch (Exception ex) {
                System.out.println("Erro ao remover modalidade selecionada: ");

            } finally {
                jpa.fecharConexao();
            }

        }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhuma modalidade selecionada! ");
        }
        

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtDescricaoBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoBuscaKeyReleased
        // TODO add your handling code here:
        String textoBusca = txtDescricaoBusca.getText().trim();
        
        if(textoBusca.isEmpty()){
            //return;
        }
                
        PersistenciaJPA jpa = new PersistenciaJPA();
        jpa.conexaoAberta();

        List<Modalidade> modalidades = jpa.getModalidades(textoBusca);
        mascaraItemLista.clear();

        for (Modalidade Modalidade : modalidades) {
            mascaraItemLista.addElement(Modalidade);

        }
        lstModalidades.setModel(mascaraItemLista);
        jpa.fecharConexao();
    }//GEN-LAST:event_txtDescricaoBuscaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModalidades().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Modalidade> lstModalidades;
    private javax.swing.JTextField txtDescricaoBusca;
    // End of variables declaration//GEN-END:variables
}
